{
  try {
    LOG.error("Exception while analyzing expression at " + DiagnosticUtils.atLocation(expression) + ":\n"+ expression.getText()+ "\n",e);
  }
 catch (  AssertionError errorFromLogger) {
    throw new KotlinFrontEndException(errorFromLogger.getMessage(),e);
  }
}
