{
  super("Rethrow stored exception",cause);
}
