{
  try {
    Assert.assertTrue(message,b);
  }
 catch (  AssertionError e) {
    assertionFailures.add(e);
  }
}
