{
  loadText("fun foo(a : Int): Boolean = a > 0 || a/0 > 0");
  Method main=generateFunction();
  assertEquals(true,main.invoke(null,5));
  boolean hadException=false;
  try {
    main.invoke(null,0);
  }
 catch (  InvocationTargetException e) {
    if (e.getTargetException() instanceof ArithmeticException) {
      hadException=true;
    }
  }
  assertTrue(hadException);
}
