{
  loadText("fun foo() { throw Exception(); }");
  final Method main=generateFunction();
  assertThrows(main,Exception.class,null);
}
