{
  try {
    Assert.assertTrue(b);
  }
 catch (  AssertionError e) {
    assertionFailures.add(e);
  }
}
