{
  loadText("fun foo(a : Int): Boolean = a > 0 && a/0 > 0");
  final Method main=generateFunction();
  assertEquals(false,main.invoke(null,0));
  boolean hadException=false;
  try {
    main.invoke(null,5);
  }
 catch (  InvocationTargetException e) {
    if (e.getTargetException() instanceof ArithmeticException) {
      hadException=true;
    }
  }
  assertTrue(hadException);
}
