{
  handleJumpInsideTryFinally(error);
  add(new ThrowExceptionInstruction(expression,getCurrentScope(),error));
}
