{
  String message;
  try {
    message=ZZ_ERROR_MSG[errorCode];
  }
 catch (  ArrayIndexOutOfBoundsException e) {
    message=ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
  }
  throw new KotlinLexerException(message + "\n at '" + yytext()+ "'\n"+ zzBuffer);
}
